### ISSUE TITLE
Error 403: Invalid or missing API key.

### ISSUE THREAD

**Issue by Delovoj** [spry-group/python-vultr#37]
Hello. Got the problem

`ERROR 403: Invalid or missing API key. Check that your API key is present and matches your assigned key.
`

changed

`API_KEY = environ.get('VULTR_KEY')`

to 

`API_KEY = 'VULTR_KEY'`

now working.

**Comment by dopry** [comment]
You explanation is insufficient to consider making a change to the library.  Please provide a more detailed bug report or submit a pull request with your changes and unit tests for them.

A detailed bug report should include sample code to produce the problem, samples of the output, and a description of what you expected to happen instead.

Generally, you need to set the VULTR_KEY environment variable or instantiate Vultr with an API_KEY for write operations.

**Comment by aranhoide** [comment]
~~The Vultr API docs specify that the API key must be passed as a header.  python-vultr has been passing it as a regular parameter instead.  This has been working fine until a few days ago.  Now Vultr seems to be strict about this at least for GET requests.~~ [P.S.: sorry, this was a red herring; I was misdiagnosing this because python-vultr 0.1.2 is reporting all 403 errors as API Key errors.  It turns out Vultr is refusing my requests when made from an IPv6 address (this is despite my having whitelisted all IPv4 and IPv6 addresses in my settings).  That might be the problem that the OP is experiencing.

**Comment by dopry** [comment]
@aranhoide, in the OP example setting API_KEY to a static string resolved the problem. Leads me to believe he has not set the environment variable. Although if we're returning incorrect errors, you should probably open an issue for that. :)

@Delovoj, can you provide more information for debugging.

**Comment by rlam3** [comment]
I'm also getting the same error. Renewing API Key does not do anything for me either.
To enable yourself to access the API go to IP Chicken and add your IP Address to the whitelist and you should be able to see it. 

👍

**Comment by dopry** [comment]
Hey guys, I cut a new release. Can you check if this is resolved?

**Comment by dopry** [comment]
closing as stale, re-open if this wasn't resolved in the latest release.
